### ISSUE TITLE
Sass Imports Issue

### ISSUE THREAD

**Issue by perryjsteward** [PredixDev/px-input-group-design#2]
Hey all,

there's an issue with all of your SASS components. in your _XXX.XXXX.scss files for all the styling components your import statements are looking inside the current directory.

i.e. @import "px-defaults-design/_settings.defaults.scss";

where it should look like the below to access the components within the bower_component directory

@import "../px-defaults-design/_settings.defaults.scss";

is there another fix for this?

Thanks,
Perry

**Comment by mdwragg** [comment]
Hi Perry,

That is intentional. Your sass build of choice should take care of that for you. Or you 'build' from the shared root of the various sass components using something like `node-sass`.

Our gulp config looks something like this:

```
const sassOptions = {
  importer: importOnce,
  importOnce: {
    index: true,
    bower: true
  }
};

....

function buildCSS(){
  return combiner.obj([
    $.sass(sassOptions),
    $.autoprefixer({
      browsers: ['last 2 versions', 'Safari 8.0'],
      cascade: false
    }),
    gulpif(!argv.debug, $.cssmin())
  ]).on('error', handleError);
}
```

The important thing is the `bower` flag in `node-import-once`. This tells `gulp` (and hence `node-sass`) where to look for our imports and where the root will be of the sass build.

Thanks for your question!
Martin.

**Comment by perryjsteward** [comment]
Thanks very much that was what i was missing from gulp!

**Comment by mdwragg** [comment]
No worries! Here is a link to our central gulpfile in our PX Yeoman component generator, just so you can see all the `requires` etc:

https://github.com/PredixDev/generator-px-comp/blob/master/app/templates/_gulpfile.js

Cheers!

**Comment by perryjsteward** [comment]
I'm having some trouble getting this working with the predix seed polymer version. Have you got an example how sass should be set for Polymer?
